sudo: required
services:
  - docker

before_install:
  - docker image build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run stephengrider/react-test npm run test -- --coverage

after_success:
  - docker image build -t stephengrider/multi-client -f ./client/Dockerfile ./client
  - docker image build -t stephengrider/multi-nginx  -f ./nginx/Dockerfile  ./nginx
  - docker image build -t stephengrider/multi-server -f ./server/Dockerfile ./server
  - docker image build -t stephengrider/multi-worker -f ./worker/Dockerfile ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push stephengrider/multi-client
  - docker push stephengrider/multi-nginx
  - docker push stephengrider/multi-server
  - docker push stephengrider/multi-worker
